// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ts.proto

#ifndef PROTOBUF_ts_2eproto__INCLUDED
#define PROTOBUF_ts_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_ts_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[4];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsUserImpl();
void InitDefaultsUser();
void InitDefaultsStatusImpl();
void InitDefaultsStatus();
void InitDefaultsPostImpl();
void InitDefaultsPost();
void InitDefaultsNewPostImpl();
void InitDefaultsNewPost();
inline void InitDefaults() {
  InitDefaultsUser();
  InitDefaultsStatus();
  InitDefaultsPost();
  InitDefaultsNewPost();
}
}  // namespace protobuf_ts_2eproto
namespace tinysocial {
class NewPost;
class NewPostDefaultTypeInternal;
extern NewPostDefaultTypeInternal _NewPost_default_instance_;
class Post;
class PostDefaultTypeInternal;
extern PostDefaultTypeInternal _Post_default_instance_;
class Status;
class StatusDefaultTypeInternal;
extern StatusDefaultTypeInternal _Status_default_instance_;
class User;
class UserDefaultTypeInternal;
extern UserDefaultTypeInternal _User_default_instance_;
}  // namespace tinysocial
namespace tinysocial {

// ===================================================================

class User : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tinysocial.User) */ {
 public:
  User();
  virtual ~User();

  User(const User& from);

  inline User& operator=(const User& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  User(User&& from) noexcept
    : User() {
    *this = ::std::move(from);
  }

  inline User& operator=(User&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const User& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const User* internal_default_instance() {
    return reinterpret_cast<const User*>(
               &_User_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(User* other);
  friend void swap(User& a, User& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline User* New() const PROTOBUF_FINAL { return New(NULL); }

  User* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const User& from);
  void MergeFrom(const User& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(User* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:tinysocial.User)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  mutable int _cached_size_;
  friend struct ::protobuf_ts_2eproto::TableStruct;
  friend void ::protobuf_ts_2eproto::InitDefaultsUserImpl();
};
// -------------------------------------------------------------------

class Status : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tinysocial.Status) */ {
 public:
  Status();
  virtual ~Status();

  Status(const Status& from);

  inline Status& operator=(const Status& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Status(Status&& from) noexcept
    : Status() {
    *this = ::std::move(from);
  }

  inline Status& operator=(Status&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Status& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Status* internal_default_instance() {
    return reinterpret_cast<const Status*>(
               &_Status_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(Status* other);
  friend void swap(Status& a, Status& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Status* New() const PROTOBUF_FINAL { return New(NULL); }

  Status* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Status& from);
  void MergeFrom(const Status& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Status* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 stat = 1;
  void clear_stat();
  static const int kStatFieldNumber = 1;
  ::google::protobuf::int32 stat() const;
  void set_stat(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:tinysocial.Status)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 stat_;
  mutable int _cached_size_;
  friend struct ::protobuf_ts_2eproto::TableStruct;
  friend void ::protobuf_ts_2eproto::InitDefaultsStatusImpl();
};
// -------------------------------------------------------------------

class Post : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tinysocial.Post) */ {
 public:
  Post();
  virtual ~Post();

  Post(const Post& from);

  inline Post& operator=(const Post& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Post(Post&& from) noexcept
    : Post() {
    *this = ::std::move(from);
  }

  inline Post& operator=(Post&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Post& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Post* internal_default_instance() {
    return reinterpret_cast<const Post*>(
               &_Post_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(Post* other);
  friend void swap(Post& a, Post& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Post* New() const PROTOBUF_FINAL { return New(NULL); }

  Post* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Post& from);
  void MergeFrom(const Post& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Post* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // string postText = 3;
  void clear_posttext();
  static const int kPostTextFieldNumber = 3;
  const ::std::string& posttext() const;
  void set_posttext(const ::std::string& value);
  #if LANG_CXX11
  void set_posttext(::std::string&& value);
  #endif
  void set_posttext(const char* value);
  void set_posttext(const char* value, size_t size);
  ::std::string* mutable_posttext();
  ::std::string* release_posttext();
  void set_allocated_posttext(::std::string* posttext);

  // int32 time = 2;
  void clear_time();
  static const int kTimeFieldNumber = 2;
  ::google::protobuf::int32 time() const;
  void set_time(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:tinysocial.Post)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr posttext_;
  ::google::protobuf::int32 time_;
  mutable int _cached_size_;
  friend struct ::protobuf_ts_2eproto::TableStruct;
  friend void ::protobuf_ts_2eproto::InitDefaultsPostImpl();
};
// -------------------------------------------------------------------

class NewPost : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tinysocial.NewPost) */ {
 public:
  NewPost();
  virtual ~NewPost();

  NewPost(const NewPost& from);

  inline NewPost& operator=(const NewPost& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  NewPost(NewPost&& from) noexcept
    : NewPost() {
    *this = ::std::move(from);
  }

  inline NewPost& operator=(NewPost&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const NewPost& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NewPost* internal_default_instance() {
    return reinterpret_cast<const NewPost*>(
               &_NewPost_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(NewPost* other);
  friend void swap(NewPost& a, NewPost& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline NewPost* New() const PROTOBUF_FINAL { return New(NULL); }

  NewPost* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const NewPost& from);
  void MergeFrom(const NewPost& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(NewPost* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string postFrom = 1;
  void clear_postfrom();
  static const int kPostFromFieldNumber = 1;
  const ::std::string& postfrom() const;
  void set_postfrom(const ::std::string& value);
  #if LANG_CXX11
  void set_postfrom(::std::string&& value);
  #endif
  void set_postfrom(const char* value);
  void set_postfrom(const char* value, size_t size);
  ::std::string* mutable_postfrom();
  ::std::string* release_postfrom();
  void set_allocated_postfrom(::std::string* postfrom);

  // string postTo = 2;
  void clear_postto();
  static const int kPostToFieldNumber = 2;
  const ::std::string& postto() const;
  void set_postto(const ::std::string& value);
  #if LANG_CXX11
  void set_postto(::std::string&& value);
  #endif
  void set_postto(const char* value);
  void set_postto(const char* value, size_t size);
  ::std::string* mutable_postto();
  ::std::string* release_postto();
  void set_allocated_postto(::std::string* postto);

  // string postText = 3;
  void clear_posttext();
  static const int kPostTextFieldNumber = 3;
  const ::std::string& posttext() const;
  void set_posttext(const ::std::string& value);
  #if LANG_CXX11
  void set_posttext(::std::string&& value);
  #endif
  void set_posttext(const char* value);
  void set_posttext(const char* value, size_t size);
  ::std::string* mutable_posttext();
  ::std::string* release_posttext();
  void set_allocated_posttext(::std::string* posttext);

  // @@protoc_insertion_point(class_scope:tinysocial.NewPost)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr postfrom_;
  ::google::protobuf::internal::ArenaStringPtr postto_;
  ::google::protobuf::internal::ArenaStringPtr posttext_;
  mutable int _cached_size_;
  friend struct ::protobuf_ts_2eproto::TableStruct;
  friend void ::protobuf_ts_2eproto::InitDefaultsNewPostImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// User

// string name = 1;
inline void User::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& User::name() const {
  // @@protoc_insertion_point(field_get:tinysocial.User.name)
  return name_.GetNoArena();
}
inline void User::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tinysocial.User.name)
}
#if LANG_CXX11
inline void User::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tinysocial.User.name)
}
#endif
inline void User::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tinysocial.User.name)
}
inline void User::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tinysocial.User.name)
}
inline ::std::string* User::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:tinysocial.User.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* User::release_name() {
  // @@protoc_insertion_point(field_release:tinysocial.User.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void User::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:tinysocial.User.name)
}

// -------------------------------------------------------------------

// Status

// int32 stat = 1;
inline void Status::clear_stat() {
  stat_ = 0;
}
inline ::google::protobuf::int32 Status::stat() const {
  // @@protoc_insertion_point(field_get:tinysocial.Status.stat)
  return stat_;
}
inline void Status::set_stat(::google::protobuf::int32 value) {
  
  stat_ = value;
  // @@protoc_insertion_point(field_set:tinysocial.Status.stat)
}

// -------------------------------------------------------------------

// Post

// string name = 1;
inline void Post::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Post::name() const {
  // @@protoc_insertion_point(field_get:tinysocial.Post.name)
  return name_.GetNoArena();
}
inline void Post::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tinysocial.Post.name)
}
#if LANG_CXX11
inline void Post::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tinysocial.Post.name)
}
#endif
inline void Post::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tinysocial.Post.name)
}
inline void Post::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tinysocial.Post.name)
}
inline ::std::string* Post::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:tinysocial.Post.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Post::release_name() {
  // @@protoc_insertion_point(field_release:tinysocial.Post.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Post::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:tinysocial.Post.name)
}

// int32 time = 2;
inline void Post::clear_time() {
  time_ = 0;
}
inline ::google::protobuf::int32 Post::time() const {
  // @@protoc_insertion_point(field_get:tinysocial.Post.time)
  return time_;
}
inline void Post::set_time(::google::protobuf::int32 value) {
  
  time_ = value;
  // @@protoc_insertion_point(field_set:tinysocial.Post.time)
}

// string postText = 3;
inline void Post::clear_posttext() {
  posttext_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Post::posttext() const {
  // @@protoc_insertion_point(field_get:tinysocial.Post.postText)
  return posttext_.GetNoArena();
}
inline void Post::set_posttext(const ::std::string& value) {
  
  posttext_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tinysocial.Post.postText)
}
#if LANG_CXX11
inline void Post::set_posttext(::std::string&& value) {
  
  posttext_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tinysocial.Post.postText)
}
#endif
inline void Post::set_posttext(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  posttext_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tinysocial.Post.postText)
}
inline void Post::set_posttext(const char* value, size_t size) {
  
  posttext_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tinysocial.Post.postText)
}
inline ::std::string* Post::mutable_posttext() {
  
  // @@protoc_insertion_point(field_mutable:tinysocial.Post.postText)
  return posttext_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Post::release_posttext() {
  // @@protoc_insertion_point(field_release:tinysocial.Post.postText)
  
  return posttext_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Post::set_allocated_posttext(::std::string* posttext) {
  if (posttext != NULL) {
    
  } else {
    
  }
  posttext_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), posttext);
  // @@protoc_insertion_point(field_set_allocated:tinysocial.Post.postText)
}

// -------------------------------------------------------------------

// NewPost

// string postFrom = 1;
inline void NewPost::clear_postfrom() {
  postfrom_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& NewPost::postfrom() const {
  // @@protoc_insertion_point(field_get:tinysocial.NewPost.postFrom)
  return postfrom_.GetNoArena();
}
inline void NewPost::set_postfrom(const ::std::string& value) {
  
  postfrom_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tinysocial.NewPost.postFrom)
}
#if LANG_CXX11
inline void NewPost::set_postfrom(::std::string&& value) {
  
  postfrom_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tinysocial.NewPost.postFrom)
}
#endif
inline void NewPost::set_postfrom(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  postfrom_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tinysocial.NewPost.postFrom)
}
inline void NewPost::set_postfrom(const char* value, size_t size) {
  
  postfrom_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tinysocial.NewPost.postFrom)
}
inline ::std::string* NewPost::mutable_postfrom() {
  
  // @@protoc_insertion_point(field_mutable:tinysocial.NewPost.postFrom)
  return postfrom_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NewPost::release_postfrom() {
  // @@protoc_insertion_point(field_release:tinysocial.NewPost.postFrom)
  
  return postfrom_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NewPost::set_allocated_postfrom(::std::string* postfrom) {
  if (postfrom != NULL) {
    
  } else {
    
  }
  postfrom_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), postfrom);
  // @@protoc_insertion_point(field_set_allocated:tinysocial.NewPost.postFrom)
}

// string postTo = 2;
inline void NewPost::clear_postto() {
  postto_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& NewPost::postto() const {
  // @@protoc_insertion_point(field_get:tinysocial.NewPost.postTo)
  return postto_.GetNoArena();
}
inline void NewPost::set_postto(const ::std::string& value) {
  
  postto_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tinysocial.NewPost.postTo)
}
#if LANG_CXX11
inline void NewPost::set_postto(::std::string&& value) {
  
  postto_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tinysocial.NewPost.postTo)
}
#endif
inline void NewPost::set_postto(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  postto_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tinysocial.NewPost.postTo)
}
inline void NewPost::set_postto(const char* value, size_t size) {
  
  postto_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tinysocial.NewPost.postTo)
}
inline ::std::string* NewPost::mutable_postto() {
  
  // @@protoc_insertion_point(field_mutable:tinysocial.NewPost.postTo)
  return postto_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NewPost::release_postto() {
  // @@protoc_insertion_point(field_release:tinysocial.NewPost.postTo)
  
  return postto_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NewPost::set_allocated_postto(::std::string* postto) {
  if (postto != NULL) {
    
  } else {
    
  }
  postto_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), postto);
  // @@protoc_insertion_point(field_set_allocated:tinysocial.NewPost.postTo)
}

// string postText = 3;
inline void NewPost::clear_posttext() {
  posttext_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& NewPost::posttext() const {
  // @@protoc_insertion_point(field_get:tinysocial.NewPost.postText)
  return posttext_.GetNoArena();
}
inline void NewPost::set_posttext(const ::std::string& value) {
  
  posttext_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tinysocial.NewPost.postText)
}
#if LANG_CXX11
inline void NewPost::set_posttext(::std::string&& value) {
  
  posttext_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tinysocial.NewPost.postText)
}
#endif
inline void NewPost::set_posttext(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  posttext_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tinysocial.NewPost.postText)
}
inline void NewPost::set_posttext(const char* value, size_t size) {
  
  posttext_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tinysocial.NewPost.postText)
}
inline ::std::string* NewPost::mutable_posttext() {
  
  // @@protoc_insertion_point(field_mutable:tinysocial.NewPost.postText)
  return posttext_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* NewPost::release_posttext() {
  // @@protoc_insertion_point(field_release:tinysocial.NewPost.postText)
  
  return posttext_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void NewPost::set_allocated_posttext(::std::string* posttext) {
  if (posttext != NULL) {
    
  } else {
    
  }
  posttext_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), posttext);
  // @@protoc_insertion_point(field_set_allocated:tinysocial.NewPost.postText)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace tinysocial

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ts_2eproto__INCLUDED
